server:
  port: 7801
spring:
  cloud:
    config:
      env: dev
      label: master
      discovery:
        enabled: true
        serviceId: cloud-configserver
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@peer1:8761/eureka/
feign:
  hystrix:
    enabled: true