server:
  port: 7801
spring:
  application:
    name: cloud-goods
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
feign:
  hystrix:
    enabled: true